name: csharp_rpc
description: Execute C# code from Dart (Flutter) application.
version: 0.0.1
maintainer: Yehuda Kremer (yehudakremer@gmail.com)
homepage: https://github.com/YehudaKremer/csharp_rpc
issue_tracker: https://github.com/YehudaKremer/csharp_rpc/issues

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
